[package]
name = "proxyengine"
version = "0.1.0"
authors = ["Rainer Stademann <rainer.stademann@silverengine.de>"]

#[workspace]
#members=["../../gitclones/NetBricks/framework", "test/framework-test"]

[dependencies]
e2d2 = { path = "../../gitclones/NetBricks/framework", features = ["performance"] }
rand = "0.3"
fnv = "*"
log = "0.3"
env_logger = "0.3"
nix = "0.10.0"
ctrlc = { version = "~3", features = ["termination"] }
time = ">=0.1.0"
ipnet = "1.0"

[features]

